### ISSUE TITLE
[CMSConnect] MG seg faults

### ISSUE THREAD

**Issue by AndreasAlbert** [cms-sw/genproductions#1842]
Hi,

I keep getting seg faults for one of 400 MG subprocesses of my gridpack (full log at [1], subprocess log showing the seg fault at [2]). I do not get this error if I run in local mode, so I think it may be related to CMSConnect, but I have no good idea how to debug it seeing that there is so little information available in the logs.

@khurtado do you have any ideas for this one?

[1] https://gist.github.com/AndreasAlbert/b1105a66e52c792130b2d7d1fe47a340
[2] https://gist.github.com/AndreasAlbert/ae6659c7646a7531bb4066145e023a5d

**Comment by AndreasAlbert** [comment]
Also, for some mass points, I get 

`../madevent_mintMC: error while loading shared libraries: libquadmath.so.0: cannot open shared object file: No such file or director`

which was also discussed at #1177 for the CERN batch system.

Is this library available on all CMSConnect nodes?

**Comment by AndreasAlbert** [comment]
Thanks, I will try the PR and get back to you. It may take a while since the jobs run for hours before failing.

As for the libquadmath: The grid jobs fail immediately and massively, see the log at  [1], interesting part is starting at line 1065.

[1] https://gist.github.com/AndreasAlbert/580b2cd98f7767bdfc425b5be09e42de#file-dmsimp_dm_zll_nlo_vector_gq0p25_gdm1p0_my1-1000_mxd-450p0-log-L1065

**Comment by khurtado** [comment]
Okay, that is weird because I can see jobs related to that card failing with Exit Code 127 (due to libquadmath not being found), but condor seems to be propagating the environment just fine, so the same PR above is probably again the best way to find out what the environment was at execution time.

**Comment by AndreasAlbert** [comment]
I ran with the PR and now observed a failure with this subprocess error message:
```
At line 132 of file configs_and_props_inc_chooser.f
Fortran runtime error: Bad integer for item 4 in list input
```
Here, MG tries to parse the `SubProcesses/P0_ccx_epemxdxdxg/GF2/configs_and_props_info.dat` file and fails because line 17496 contains a brace that should not be there:

```
M      7     -3  0  80( `        55
```

All relevant files including the subprocess log are at [1]. The environment dump seems to work now. I have no idea whether this is related to the seg fault problem. The failing FORTRAN line looks like this:
````
read(buff(2:),*) i,j,k,id
````

which to me looks like it may segfault under certain circumstances, although I do not know enough about FORTRAN to say for sure.

I will run another gridpack to see if I can reproduce the seg fault again.


[1] /afs/cern.ch/work/a/aalbert/public/share/2018-08-02_mg_segfault/logs1

**Comment by khurtado** [comment]
Argh, thanks. I will ping the OSG team regarding that and keep you in the loop.

**Comment by khurtado** [comment]
@AndreasAlbert stash should be working again. The node had to be rebooted though.

**Comment by AndreasAlbert** [comment]
Thanks @khurtado, it still does not really work though: `/stash/` seems to be empty, so trying to create `/stash/user/aalbert` fails

**Comment by khurtado** [comment]
@AndreasAlbert Bad timing. They just re-implemented stash to work on NFS, so there was another 30 minutes downtime. Could you try again?

**Comment by AndreasAlbert** [comment]
@khurtado It worked for a bit, but now `/stash/` only has one child directory again, `cvmfs`. I gather people are still working on the system? Let's try again tomorrow.

**Comment by khurtado** [comment]
@AndreasAlbert Okay, I know where the problem is, but I don't understand the reason. Maybe you can help me:

Due to the fact singularity doesn't inherit `$LD_LIBRARY_PATH` from the environment, the patch I pasted above prepends the content of `$SRT_LD_LIBRARY_PATH_SCRAMRT` on it. However, in your job, there is no `$SRT_LD_LIBRARY_PATH_SCRAMRT` but rather `$SRT_LD_LIBRARY_PATH_SCRAMRTDEL`. Do you know the reason for it? Do you know if only one of them can show up in the environment at a time?

Did you change anything in the way the CMS release is setup?
I tried to reproduce the environment by going into your gridpack as shown below, but I got the environment variable ending in `SCRAMRT`.

```
cd /local-scratch/aalbert/run/2018-07-13_monoz_dmsimp_spin1_nlo/genproductions/bin/MadGraph5_aMCatNLO/DMSimp_DM_ZLL_NLO_Vector_GQ0p25_GDM1p0_MY1-1000_MXd-250p0/DMSimp_DM_ZLL_NLO_Vector_GQ0p25_GDM1p0_MY1-1000_MXd-250p0_gridpack
eval `scram runtime -sh`
$ echo $SRT_LD_LIBRARY_PATH_SCRAMRT 
/local-scratch/aalbert/run/2018-07-13_monoz_dmsimp_spin1_nlo/genproductions/bin/MadGraph5_aMCatNLO/DMSimp_DM_ZLL_NLO_Vector_GQ0p25_GDM1p0_MY1-1000_MXd-250p0/DMSimp_DM_ZLL_NLO_Vector_GQ0p25_GDM1p0_MY1-1000_MXd-250p0_gridpack/biglib/slc6_amd64_gcc481:/local-scratch/aalbert/run/2018-07-13_monoz_dmsimp_spin1_nlo/genproductions/bin/MadGraph5_aMCatNLO/DMSimp_DM_ZLL_NLO_Vector_GQ0p25_GDM1p0_MY1-1000_MXd-250p0/DMSimp_DM_ZLL_NLO_Vector_GQ0p25_GDM1p0_MY1-1000_MXd-250p0_gridpack/lib/slc6_amd64_gcc481:/local-scratch/aalbert/run/2018-07-13_monoz_dmsimp_spin1_nlo/genproductions/bin/MadGraph5_aMCatNLO/DMSimp_DM_ZLL_NLO_Vector_GQ0p25_GDM1p0_MY1-1000_MXd-250p0/DMSimp_DM_ZLL_NLO_Vector_GQ0p25_GDM1p0_MY1-1000_MXd-250p0_gridpack/external/slc6_amd64_gcc481/lib:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_1_30/biglib/slc6_amd64_gcc481:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_1_30/lib/slc6_amd64_gcc481:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_1_30/external/slc6_amd64_gcc481/lib:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/llvm/3.4-cms2/lib:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/gcc/4.8.1/lib64:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/gcc/4.8.1/lib
[khurtado@login DMSimp_DM_ZLL_NLO_Vector_GQ0p25_GDM1p0_MY1-1000_MXd-250p0_gridpack]$ echo $SRT_LD_LIBRARY_PATH_SCRAMRTDEL
```

**Comment by khurtado** [comment]
@AndreasAlbert Anyway, could you try PR #1852 to check if this fixes this problem?

**Comment by AndreasAlbert** [comment]
Thanks for looking into it, @khurtado! I will test the PR to see what happens.

As for the environment question: I do not think I changed anything. I run the submission script at [1], from the area you see on local-scratch. The script is a trivial wrapper that calls the cmsconnect submission script. Apart from adding MG cards to the repository, the only change the the coade is in commit [2], which is a fix to a previous problem I had (doesn't really have anything to do with this process).
I can reproduce your observation that in that given directory, I do not get the DEL variable. However, I do see CMSSW trying to unset all kinds of variables ending in DEL, like `unset SRT_CMS_OPENLOOPS_PREFIX_SCRAMRTDEL`. 

@Dr15Jones Does CMSSW use environment variables ending in 'DEL' for any specific purpose?

For this issue overall, the confusing part to me is that there are multiple problems, all of which are transient. Earlier today I was again able to create one gridpack, now it does not work again because of the fortran error described above. I have not seen the libquadmath error in the last 24 hours. In the meantime I have cycled through cards, madgraph versions, etc and keep encountering the same issues. 

[1] https://github.com/AndreasAlbert/genproductions/blob/73e57e565830b4d8d2e7d9b14be2c42fdc685d68/bin/MadGraph5_aMCatNLO/submit.sh

[2] https://github.com/AndreasAlbert/genproductions/commit/53ad246d7aa06aa127d37c4942fb43b7691e8328

**Comment by AndreasAlbert** [comment]
@khurtado I think scram uses the DEL variables to manage what variables to unset. The corresponding code is at [1], but I do not know enough perl to make sense of it. Anyway, that does not tell us why the actual variable is not set. 

[1] https://github.com/cms-sw/SCRAM/blob/master/src/SCRAM/Plugins/RuntimeEnv.pm#L101

**Comment by khurtado** [comment]
@AndreasAlbert So, the `libquadmath` issue, which was systematic (all jobs failing with the same problem) is probably solved with this workaround, but you are still experiencing the random segfaults (where many subprocesses go well, but some might segfault) plus some other issues? If so, could you point me out to these other issues (or the segfaults again if there is a dump after the failures?) My guess is there might still be other environment variables messed up (still trying to understand why this would happen now if we haven't changed the CMS release at all) 

One way to check on these errors (e.g: the segfault) is having the subprocess directory in the submit node and running ajob_template, etc after doing a ``` scram `runtime -sh` ``` vs a manual setup of the environment using the worker node environment dump provided by the logfiles in the failed jobs. I tried the first method before and I couldn't reproduce the segfault, but I haven't tried the manual env setup yet. Please, point me out to your gridpack in `local-scratch` if you see the segfault again.

**Comment by Dr15Jones** [comment]
I think the `SRT_*_SCRAMRTDEL` are the values of the `*` envorinment variable before one ran `cmsenv`. They were stored so that it would be possible to restore those values if necessary.

@smuzaffar would definitely know, but he is away on vacation for a month.

**Comment by Dr15Jones** [comment]
In my work area, I do not have an environment variable named `SRT_LD_LIBRARY_PATH_SCRAMRT`, I only have `LD_LIBRARY_PATH` and `SRT_LD_LIBRARY_PATH_SCRAMRTDEL`.

**Comment by khurtado** [comment]
@Dr15Jones But E.g: `SRT_LD_LIBRARY_PATH_SCRAMRTDEL` has  cvmfs-related paths on it, so this doesn't seem to be the original `LD_LIBRARY_PATH` variable before `cmsenv`. In your work area, does `LD_LIBRARY_PATH` contain `SRT_LD_LIBRARY_PATH_SCRAMRTDEL` (E.g: SRT_LD_LIBRARY_PATH_SCRAMRTDEL=A1:B1, LD_LIBRARY_PATH=A1:B1:C1)?

**Comment by Dr15Jones** [comment]
For me, the two env variables have identical values, but I also did not have LD_LIBRARY_PATH defined before doing `cmsenv`.

**Comment by Dr15Jones** [comment]
So if I do
```
setenv LD_LIBRARY_PATH DUMMY
```
before doing `cmsenv`, then after doing `cmsenv` I get
```
SRT_LD_LIBRARY_PATH_SCRAMRT == <lots of stuff>
LD_LIBRARY_PATH == ${SRT_LD_LIBRARY_PATH_SCRAMRT}:DUMMY
```
and I do not get the env variable `SRT_LD_LIBRARY_PATH_SCRAMRTDEL`.

So it appears that the existence of `SRT_LD_LIBRARY_PATH_SCRAMRTDEL` and `SRT_LD_LIBRARY_PATH_SCRAMRT` depends on if `LD_LIBRARY_PATH` was previously set before calling `cmsenv`.

**Comment by khurtado** [comment]
@Dr15Jones Thank you! If I unset `LD_LIBRARY_PATH` before `cmsenv`, I get `SRT_LD_LIBRARY_PATH_SCRAMRTDEL`, but if I have it set (e.g: export LD_LIBRARY_PATH=:), then I get `SRT_LD_LIBRARY_PATH_SCRAMRT`. So it seems we definitely only get one or the other. 

#1852 should be fine then. The other variable that is usually important is `PATH`, AFAIK condor doesn't inherit this variable, it shouldn't be required unless madgraph tries to call gfortran or gcc before the executables at the worker node.

**Comment by smuzaffar** [comment]
@khurtado , as @Dr15Jones  wrote , SRT_* variables are set by scram and these are used to restore the original environment. the SRT_*_SCRAMRT are those which existed at the time of `cmsenv` and SRT_*_SCRAMRTDEL are those which were not set at the time of `cmsenv` and scram will unset these when one runs `scram unset -sh`

I would suggest to not depend on these SRT variables, can you set the env within singularity by running cmsenv?

**Comment by AndreasAlbert** [comment]
Hi @khurtado, it took me a while to further look at this. Because the gridpacks take a long time to run, it also takes a long time to verify whether they fail or not. With the patches you have provided, I do not see any of the original issues anymore. Thus, I would mark this issue as resolved. Thanks to you and the framework experts for your great help!
